#!/usr/bin/env python3
import subprocess
import sys
import os
import trust_boundary.errors


def main():
    output = subprocess.check_output(['git', 'diff', '--cached', '--name-only', '--diff-filter=ACM']).decode('utf-8')
    files = output.splitlines(keepends=False)
    print(f"You have changed {files}")
    name = os.environ.get("GIT_AUTHOR_NAME")
    email = os.environ.get("GIT_AUTHOR_EMAIL")
    print(f"Name: {name}, Email={email}")
    
    # raise trust_boundary.errors.ExitWithMessageError("It has all gone wrong!")


if __name__ == "__main__":
    try:
        main()
    except trust_boundary.errors.ExitWithMessageError as e:
        e.display()
        sys.exit(-1)
